server {

    listen 80;

    location / {
        proxy_pass http://hour-server:3000;
    }
}

server {
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/pyatigorets-nodejs-tasks.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pyatigorets-nodejs-tasks.ru/privkey.pem;

    location / {
        proxy_pass http://hour-server:3000;
    }
}